#!/usr/bin/env zsh
config=${CONFIG}
stream=${FCOS_STREAM}
vm_name=${VM_NAME}

usage () {
    ret=$2
    cat <<- EOF >&2
refactor-octo-chainsaw (c) 2020 Joanna Doyle
this software is not yet licensed and comes with NO WARRANTY

./configure should normally be called before this. It is also
rather unlikely you will want to run ./_run - the underscored
file contains variables such as ${VAR} for envsubst; ${var:-}
will not be touched.

Execute either as ./run or, if it is necessary to kill an
already provisioned instance, ./run -k | --kill.
EOF
    exit $ret
}

zparseopts -D -- k=remove -kill=remove h=help -help=help

[ -n "${help:-}" ] && usage $0 1
[ -n "${remove:-}" ] && gcloud compute instances delete ${vm_name:-}
gcloud compute instances create --metadata-from-file "user-data=${config:-}" --image-project "fedora-coreos-cloud" --image-family "fedora-coreos-${stream:-}" "${vm_name:-}"
